[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
# Private tasks
[tasks.coverage0]
private=true
script = "mkdir target && mkdir target/coverage && mkdir target/coverage/html"

[tasks.coverage1]
private=true
script = "CARGO_INCREMENTAL=0 RUSTFLAGS='-Cinstrument-coverage'"

[tasks.coverage2]
private=true
script = "LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw' cargo test"

[tasks.coverage3]
private=true
script = "grcov . --binary-path ./target/debug/deps/ -s . -t html --branch --ignore-not-existing --ignore '../*' --ignore '/*' -o target/coverage/html"

# Public tasks
[tasks.coverage]
run_task = {name=["coverage0", "coverage1", "coverage2", "coverage3"], fork=true}

[tasks.clean]
command = "rm"
args = [ "-rf", "target", "default.profraw"]
